// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://exjexjbtipgdlmqluvcs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV4amV4amJ0aXBnZGxtcWx1dmNzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2NzY0NDYsImV4cCI6MjA3MTI1MjQ0Nn0.d-hKwAZwIHBUKzDgQWpxFDVdzZD5abXxDUhnKwwaViE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});